ALL_PERMISSIONS = {
    'workspace.settings.view',
    'workspace.settings.edit',
    'workspace.billing',
    'workspace.delete',
    'workspace.members.invite',
    'workspace.members.remove',
    'workspace.members.view',
    'workspace.roles.create',
    'workspace.roles.edit',
    'workspace.roles.delete',
    'workspace.roles.assign',
    'room.pm_access',
    'room.crm_access',
    'project.create',
    'project.view',
    'project.edit',
    'project.delete',
    'project.archive',
    'project.members.add',
    'project.members.remove',
    'sprint.view',
    'sprint.create',
    'sprint.manage',
    'sprint.delete',
    'task.create',
    'task.create_personal',
    'task.view',
    'task.edit_own',
    'task.edit_any',
    'task.assign_others',
    'task.delete',
    'task.log_time',
    'task.manage_status_columns',
    'milestone.view',
    'milestone.create',
    'milestone.edit',
    'milestone.delete',
    'doc.view',
    'doc.create',
    'doc.edit',
    'doc.delete',
    'doc.view_private',
    'doc.manage_access',
    'doc.approve',
    'doc.templates.view',
    'doc.templates.manage',
    'crm.view',
    'crm.edit',
    'crm.delete',
    'crm.deals.view',
    'crm.deals.edit',
    'crm.deals.delete',
    'crm.deals.convert',
    'crm.pipeline.manage',
    'crm.interactions.view',
    'crm.interactions.create',
    'crm.reports.view',
    'notification.view_all',
}


def permissions_with_prefix(prefix: str) -> set[str]:
    return {permission for permission in ALL_PERMISSIONS if permission.startswith(prefix)}


OWNER_PERMISSIONS = set(ALL_PERMISSIONS)

ADMIN_PERMISSIONS = OWNER_PERMISSIONS - {'workspace.billing', 'workspace.delete'}

MANAGER_PERMISSIONS = {
    'workspace.members.invite',
    'workspace.members.view',
    'room.pm_access',
    'room.crm_access',
    'project.create',
    'project.view',
    'project.edit',
    'project.archive',
    'project.members.add',
    'project.members.remove',
    'sprint.view',
    'sprint.create',
    'sprint.manage',
    'task.create',
    'task.create_personal',
    'task.view',
    'task.edit_own',
    'task.edit_any',
    'task.assign_others',
    'task.delete',
    'task.log_time',
    'task.manage_status_columns',
    'milestone.view',
    'milestone.create',
    'milestone.edit',
    'milestone.delete',
    'doc.view',
    'doc.create',
    'doc.edit',
    'doc.delete',
    'doc.manage_access',
    'doc.approve',
    'doc.templates.view',
    'crm.view',
    'crm.edit',
    'crm.delete',
    'crm.deals.view',
    'crm.deals.edit',
    'crm.deals.delete',
    'crm.deals.convert',
    'crm.pipeline.manage',
    'crm.interactions.view',
    'crm.interactions.create',
    'crm.reports.view',
}

MEMBER_PERMISSIONS = {
    'task.create',
    'task.create_personal',
    'task.view',
    'task.edit_own',
    'task.log_time',
    'doc.view',
    'doc.create',
    'doc.edit',
    'doc.templates.view',
}

GUEST_PERMISSIONS = {
    'doc.view',
    'doc.templates.view',
}

SYSTEM_ROLE_PERMISSIONS = {
    'Owner': OWNER_PERMISSIONS,
    'Admin': ADMIN_PERMISSIONS,
    'Manager': MANAGER_PERMISSIONS,
    'Member': MEMBER_PERMISSIONS,
    'Guest': GUEST_PERMISSIONS,
}

SYSTEM_ROLE_COLORS = {
    'Owner': '#ef4444',
    'Admin': '#f97316',
    'Manager': '#3b82f6',
    'Member': '#22c55e',
    'Guest': '#6b7280',
}
